name: mauafood_front
description: Mauá Food.

publish_to: 'none'

version: 1.4.15+47

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  intl: ^0.18.0
  dartz: ^0.10.1
  enum_to_string: ^2.0.1
  google_fonts: ^4.0.4
  network_image_mock: ^2.1.1
  uuid: ^3.0.6
  cpf_cnpj_validator: ^2.0.0
  mask_text_input_formatter: ^2.4.0
  hive_flutter: ^1.1.0
  url_launcher: ^6.1.6
  dio: ^4.0.4
  font_awesome_flutter: ^10.4.0
  flutter_mobx: ^2.0.6+5
  mobx: ^2.1.4
  http: ^0.13.5
  currency_text_input_formatter: ^2.1.10
  image_picker: ^1.0.0
  path_provider: ^2.0.15
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  modular_test: ^2.0.0
  flutter_launcher_icons: ^0.10.0
  build_runner: ^2.3.3
  mobx_codegen: ^2.2.0
  mockito: ^5.3.2

flutter:
  uses-material-design: true

scripts:
  build: flutter pub run build_runner build
  watch: flutter pub run build_runner watch --delete-conflicting-outputs
flutter_intl:
  enabled: true
