// Mocks generated by Mockito 5.3.2 from annotations
// in mauafood_front/test/app/modules/menu/domain/usecases/get_meal_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mauafood_front/app/modules/menu/domain/entities/product.dart'
    as _i6;
import 'package:mauafood_front/app/modules/menu/domain/errors/errors.dart'
    as _i5;
import 'package:mauafood_front/app/modules/menu/domain/infra/menu_repository_interface.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MenuRepositoryInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockMenuRepositoryInterface extends _i1.Mock
    implements _i3.MenuRepositoryInterface {
  MockMenuRepositoryInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> getAllMeals() => (super.noSuchMethod(
        Invocation.method(
          #getAllMeals,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>> getBibaMeals() =>
      (super.noSuchMethod(
        Invocation.method(
          #getBibaMeals,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Product>>(
          this,
          Invocation.method(
            #getBibaMeals,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>> getHMeals() =>
      (super.noSuchMethod(
        Invocation.method(
          #getHMeals,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Product>>(
          this,
          Invocation.method(
            #getHMeals,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>> getMolezaMeals() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMolezaMeals,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Product>>(
          this,
          Invocation.method(
            #getMolezaMeals,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>>);
}
