default_platform(:ios)

platform :ios do
  desc "Submit a new Beta Build to TestFlight"
  lane :homolog do
    api_key = app_store_connect_api_key(
      key_id: ENV['API_KEY_ID'],
      issuer_id: ENV['ISSUER_ID'],
      key_content: ENV['API_PRIVATE_KEY'],
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )

    upload_to_testflight(
      api_key: api_key,
      changelog: 'Testar todas as funcionalidades do app',
      distribute_external: true,
      groups: ['devers'],
      notify_external_testers: true,
      ipa: ENV['APP_PATH'],
      skip_waiting_for_build_processing: false,
      submit_beta_review: true,
      reject_build_waiting_for_review: true
    )
  end

  desc "Submit to App Store"
  lane :prod do
    api_key = app_store_connect_api_key(
      key_id: ENV['API_KEY_ID'],
      issuer_id: ENV['ISSUER_ID'],
      key_content: ENV['API_PRIVATE_KEY'],
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )

    upload_to_app_store(
      api_key: api_key,
      ipa: ENV['APP_PATH'],
      precheck_include_in_app_purchases: false,
      submit_for_review: true,
      force: true, # Skip HTMl report verification
      automatic_release: true,
      skip_screenshots: true,
      submission_information: { add_id_info_uses_idfa: false }
    )
  end
end
