// Mocks generated by Mockito 5.3.2 from annotations
// in mauafood_front/test/app/modules/cart/infra/repository/cart_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mauafood_front/app/modules/cart/infra/datasources/cart_datasource_interface.dart'
    as _i2;
import 'package:mauafood_front/app/modules/cart/infra/models/cart_item_model.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CartDatasourceInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartDatasourceInterface extends _i1.Mock
    implements _i2.CartDatasourceInterface {
  MockCartDatasourceInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> postCartDemand(List<_i4.CartItemModel>? list) =>
      (super.noSuchMethod(
        Invocation.method(
          #postCartDemand,
          [list],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
