// Mocks generated by Mockito 5.3.2 from annotations
// in mauafood_front/test/app/modules/auth/presenter/bloc/register/bloc/register_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mauafood_front/app/modules/auth/domain/errors/auth_errors.dart'
    as _i5;
import 'package:mauafood_front/app/modules/auth/domain/usecases/confirm_email.dart'
    as _i7;
import 'package:mauafood_front/app/modules/auth/domain/usecases/register_user.dart'
    as _i3;
import 'package:mauafood_front/app/modules/auth/domain/usecases/resend_confirmation_code.dart'
    as _i8;
import 'package:mauafood_front/app/modules/auth/infra/models/user_model.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RegisterUserInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterUserInterface extends _i1.Mock
    implements _i3.RegisterUserInterface {
  MockRegisterUserInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.RegisterError, bool>> call(_i6.UserModel? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [user],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.RegisterError, bool>>.value(
            _FakeEither_0<_i5.RegisterError, bool>(
          this,
          Invocation.method(
            #call,
            [user],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.RegisterError, bool>>);
}

/// A class which mocks [ConfirmEmailInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfirmEmailInterface extends _i1.Mock
    implements _i7.ConfirmEmailInterface {
  MockConfirmEmailInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.ConfirmationEmailError, bool>> call(
    String? email,
    String? confirmationCode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            email,
            confirmationCode,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.ConfirmationEmailError, bool>>.value(
                _FakeEither_0<_i5.ConfirmationEmailError, bool>(
          this,
          Invocation.method(
            #call,
            [
              email,
              confirmationCode,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.ConfirmationEmailError, bool>>);
}

/// A class which mocks [ResendConfirmationCodeInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockResendConfirmationCodeInterface extends _i1.Mock
    implements _i8.ResendConfirmationCodeInterface {
  MockResendConfirmationCodeInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.ResendCodeError, void>> call(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [email],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.ResendCodeError, void>>.value(
            _FakeEither_0<_i5.ResendCodeError, void>(
          this,
          Invocation.method(
            #call,
            [email],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.ResendCodeError, void>>);
}
