name: Build & Deploy to Play Store
on:
  push:
    paths:
      - 'pubspec.yaml'
    branches:
      - dev
      - homolog
      - prod

jobs:
  fastlane-deploy_play_store:
    if: contains(github.event.head_commit.message, 'bump version')
    name: Build & Deploy to Play Store
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    permissions:
        id-token: write
        contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java Version
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter Version
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.13.1"

      - name: Get flutter dependencies
        run: flutter pub get
      
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: sa-east-1
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsRole
          role-session-name: github-action
  
      - run: npm install -g @aws-amplify/cli
      - name: Setup Amplify projects
        run: |
          AWSCLOUDFORMATIONCONFIG="{\
          \"configLevel\":\"general\",\
          \"useProfile\":true,\
          \"profileName\":\"default\",\
          \"accessKeyId\":\"${{ env.AWS_ACCESS_KEY_ID}}\",\
          \"secretAccessKey\":\"${{ env.AWS_SECRET_ACCESS_KEY}}\",\
          \"region\":\"sa-east-1\"\
          }"
          CONFIG="{\
          \"ResDir\":\"lib\"\
          }"
          FRONTEND="{\
          \"frontend\":\"flutter\",\
          \"config\":$CONFIG\
          }"
          AMPLIFY="{\
          \"projectName\":\"${{ secrets.AMPLIFY_AUTH_PROJECT }}\",\
          \"appId\":\"${{ secrets.AMPLIFY_AUTH_APP_ID }}\",\
          \"envName\":\"${{ github.ref_name }}\",\
          \"defaultEditor\":\"code\"\
          }"
          PROVIDERS="{\
          \"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
          }"
       
          amplify pull --amplify $AMPLIFY --frontend $FRONTEND --providers $PROVIDERS --yes

      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
          bundler-cache: true
          working-directory: android

      - name: Configure Keystore
        run: |
          echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/upload-keystore.jks
          echo "storeFile=upload-keystore.jks" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
        env:
          PLAY_STORE_UPLOAD_KEY: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASS }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASS }}
        working-directory: android

      - name: Build Version
        run: cat pubspec.yaml | grep -o 'version:[^:]*' | cut -f2 -d":" | xargs

      - name: Build appbundle
        run: flutter build appbundle --release --dart-define=S3_ASSETS_BASE_URL=${{ vars.AWS_BUCKET_ASSETS }} --dart-define=MSS_PRODUCT=${{ vars.MSS_PRODUCT }} --dart-define=WSS_ORDER=${{ vars.WSS_ORDER}}

      - name: Exec fastlane
        run: bundle exec fastlane ${{ github.ref_name }}
        env:
          PLAY_STORE_CONFIG_JSON: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
        working-directory: android