name: Deploy Play Store Intern Test

on:
  push:
    branches:
      - develop
jobs:
    release:
      name: Release

      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v1

        - name: Setup Java
          uses: actions/setup-java@v1
          with:
            java-version: '12.x'

        - name: Setup Flutter
          uses: subosito/flutter-action@v1
          with:
            channel: beta

        - name: Download Android keystore
          id: android_keystore
          uses: timheuer/base64-to-file@v1.0.3
          with:
            fileName: key.jks
            encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

        - name: Create key.properties
          run: |
            echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
            echo "storePassword=${{ secrets.KEYSTORE_PASS }}" >> android/key.properties
            echo "keyPassword=${{ secrets.KEYSTORE_KEY_PASS }}" >> android/key.properties
            echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties
        - name: Build Android App Bundle
          run: flutter build appbundle

        - name: Setup Ruby
          uses: actions/setup-ruby@v1
          with:
            ruby-version: '2.6'

        - name: Cache bundle dependencies
          uses: actions/cache@v2
          with:
            path: vendor/bundle
            key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
            restore-keys: ${{ runner.os }}-gems-

        - name: Download bundle dependencies
          run: |
            gem install bundler:2.0.2
            bundle config path vendor/bundle
            bundle install
        - name: Release to Google Play (beta)
          env:
            SUPPLY_PACKAGE_NAME: ${{ secrets.ANDROID_PACKAGE_NAME }}
            SUPPLY_JSON_KEY_DATA: ${{ secrets.PLAY_STORE_API }}
          run: |
            bundle exec fastlane supply \
            --aab build/app/outputs/bundle/release/app-release.aab \
            --track internal
